[workspace]
members = ["crates/*", "packages/create"]
resolver = "3"

[workspace.package]
edition = "2024"
homepage = "https://github.com/janustack"
license = "MIT"
readme = "README.md"
repository = "https://github.com/janustack/create-janustack"