# https://moonrepo.dev/docs/config/project
$schema: https://moonrepo.dev/schemas/project.json

fileGroups:
  artifacts:
    - "target/**/*"
    - "*.node"
  sources:
    - "src/**/*"
    - "index.*"
    - "*.rs"

tasks:
  artifacts:
    command: napi artifacts
    description: Generate artifacts for the package.

  build:
    command: napi build --platform --release
    description: Build the package for the specified platform and target.
    inputs:
      - "@globs(sources)"
    outputs:
      - "@globs(artifacts)"

  debug:
    command: napi build --platform
    description: Build the package for the specified platform in debug mode.
    outputs:
      - "@globs(artifacts)"

  prepublishOnly:
    command: napi prepublish -t npm
    description: Run prepublish checks and prepare the package for publishing.

  universal:
    command: napi universal
    description: Build the package for all platforms.

  version:
    command: napi version
    description: Bump the package version.
    inputs:
      - package.json
