# https://moonrepo.dev/docs/config/tasks
$schema: https://moonrepo.dev/schemas/tasks.json

tasks:
  build:
    description: Build the application.
    command: vite build
    outputs:
      - dist

  dev:
    description: Start the development server.
    command: vite dev

  preview:
    description: Serve the production build of the application.
    command: vite preview
    deps:
      - build
    preset: server
