name: Build and Publish Docker Images (napi-rs)

permissions:
  contents: read
  id-token: write
  packages: write

on:
  workflow_dispatch:

jobs:
  build-and-push-images:
    name: Build and Push Images
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
        - name: alpine-zig
          needs_libcxx: false
        - name: alpine
          needs_libcxx: false
        - name: debian-aarch64
          needs_libcxx: true
        - name: debian-zig
          needs_libcxx: false
        - name: debian
          needs_libcxx: false
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.JANUSTACK_GHCR_TOKEN }}
      
      # Only run this step for debian-aarch64 images
      - name: Install latest libc++-dev for cross build
        if: matrix.needs_libcxx == true
        uses: addnab/docker-run-action@v3
        with:
          image: node:slim
          options: '--platform linux/arm64 --user 0:0 -e GITHUB_TOKEN -v ${{ github.workspace }}/lib/llvm-18:/usr/lib/llvm-18'
          run: >-
            apt update &&
            apt install -y wget gnupg2 &&
            wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - &&
            echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-18 main" >> /etc/apt/sources.list &&
            echo "deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-18 main" >> /etc/apt/sources.list &&
            apt update &&
            apt install libc++-18-dev libc++abi-18-dev -y --fix-missing --no-install-recommends &&
            rm /usr/lib/llvm-18/lib/libc++abi.so

      - name: Build and push ${{ matrix.name }} image
        uses: docker/build-push-action@v6
        with:
          file: docker/${{ matrix.name }}.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/janustack/create-janustack/napi-rs:${{ matrix.name }}